[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino

lib_deps =
  adafruit/Adafruit BME280 Library
  adafruit/Adafruit Unified Sensor
  adafruit/Adafruit BH1750 Library
  sensirion/Sensirion I2C SGP41

build_flags =
  -DARDUINO_ARCH_ESP32
